apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: backend
status:
  loadBalancer: {}
